.gitignore, src/main/java/soongsil/kidbean/server/mypage/domain/Member.java, src/main/java/soongsil/kidbean/server/quiz/domain/Analysis.java, src/main/java/soongsil/kidbean/server/quiz/domain/AnswerQuiz.java, src/main/java/soongsil/kidbean/server/quiz/domain/ImageQuiz.java, src/main/java/soongsil/kidbean/server/quiz/domain/ImageQuizSolved.java, src/main/java/soongsil/kidbean/server/quiz/domain/RecordQuizSolved.java, src/main/java/soongsil/kidbean/server/quiz/domain/SentenceQuiz.java, src/main/java/soongsil/kidbean/server/quiz/domain/Word.java, src/main/java/soongsil/kidbean/server/quiz/domain/type/Category.java, src/main/java/soongsil/kidbean/server/quiz/domain/type/Level.java, src/main/resources/application.properties, src/main/resources/application.yml
- Resolves #1 
> 초기 설정
- 각각의 엔티티 별 초기 설정 진행
- yml 파일도 초기 설정 완료
=> feat: 초기 엔티티 설정

src/main/java/soongsil/kidbean/server/global/application/S3Uploader.java, src/main/java/soongsil/kidbean/server/quiz/application/S3Uploader.java, src/main/java/soongsil/kidbean/server/quiz/dto/response/ImageQuizMemberDetailResponse.java, src/test/java/soongsil/kidbean/server/config/AwsS3MockConfig.java, src/test/java/soongsil/kidbean/server/quiz/S3UploaderTest.java
-  #4 
> s3 관련 기능 최적화
- ImageInfo embedded 객체 생성
- s3 파일 삭제 ImageInfo 이용
=> refactor: s3 관련 기능 최적화

src/main/java/soongsil/kidbean/server/global/config/S3Config.java, src/main/java/soongsil/kidbean/server/global/vo/ImageInfo2.java, src/main/java/soongsil/kidbean/server/program/application/ProgramService.java, src/main/java/soongsil/kidbean/server/program/domain/Program.java, src/main/java/soongsil/kidbean/server/program/dto/ProgramRequest.java, src/main/java/soongsil/kidbean/server/program/presentation/ProgramController.java, src/main/java/soongsil/kidbean/server/program/repository/ProgramRepository.java
- Resolves [FEAT] 이미지 퀴즈 개발 #9
> 프로그램 조회 기능 관련 개발 
- 엔티티 수정 
- VO 추가 
- 프로그램 조회 기능
=> feat: 프로그램 조회 관련 기능 개발

src/main/java/soongsil/kidbean/server/mypage/application/QuizSolvedService.java, src/main/java/soongsil/kidbean/server/mypage/dto/response/SolvedImageDetailResponse.java, src/main/java/soongsil/kidbean/server/mypage/dto/response/SolvedImageInfo.java, src/main/java/soongsil/kidbean/server/mypage/dto/response/SolvedImageListResponse.java, src/main/java/soongsil/kidbean/server/mypage/dto/response/SolvedRecordInfo.java, src/main/java/soongsil/kidbean/server/mypage/dto/response/SolvedRecordListResponse.java, src/main/java/soongsil/kidbean/server/mypage/presentation/QuizSolvedController.java, src/main/java/soongsil/kidbean/server/quiz/repository/ImageQuizSolvedRepository.java, src/main/java/soongsil/kidbean/server/quiz/repository/RecordQuizSolvedRepository.java, src/test/java/soongsil/kidbean/server/mypage/controller/QuizSolvedTest.java
- Resolves #5
> 해당 멤버의 이미지 맞추기 목록 + 문제 세부사항 개발
- 푼 이미지 맞추기 전체 목록 구현
- 이미지 맞추기 세부 사항 API 구현
- 푼 문장 맞추기 전체 목록 구현
- 푼 AnswerQuiz 맞추기 전체 목록 구현
=> feat: 멤버의 이미지 맞추기 구현

src/main/java/soongsil/kidbean/server/member/presentation/QuizSolvedController.java
> api 주소명 수정
- api 주소명 잘 못 작성한거 변경
=> refactor: api 주소명 수정

src/main/java/soongsil/kidbean/server/ServerApplication.java, src/main/java/soongsil/kidbean/server/member/application/MypageService.java, src/main/java/soongsil/kidbean/server/member/domain/Member.java, src/main/java/soongsil/kidbean/server/member/dto/response/SolvedImageInfo.java, src/main/java/soongsil/kidbean/server/member/dto/response/SolvedWordDetailResponse.java, src/main/java/soongsil/kidbean/server/quiz/domain/ImageQuiz.java, src/main/java/soongsil/kidbean/server/quiz/domain/QuizSolved.java, src/main/java/soongsil/kidbean/server/quiz/domain/type/Level.java, src/main/java/soongsil/kidbean/server/quiz/repository/QuizSolvedRepository.java, src/main/java/soongsil/kidbean/server/summary/application/AverageScoreScheduler.java, src/main/java/soongsil/kidbean/server/summary/domain/AverageScore.java, src/main/java/soongsil/kidbean/server/summary/domain/ImageQuizScore.java, src/main/java/soongsil/kidbean/server/summary/domain/type/AgeGroup.java, src/main/java/soongsil/kidbean/server/summary/repository/AverageScoreRepository.java, src/main/java/soongsil/kidbean/server/summary/repository/ImageQuizScoreRepository.java
> 자동 레벨 변경 기능 구현
- 자동 레벨 변경 기능 구현
- wordQuiz detail 구현 완료
=> feat: 자동 레벨 변경 기능 구현

src/main/java/soongsil/kidbean/server/quiz/application/AnswerQuizSolvedService.java, src/main/java/soongsil/kidbean/server/quiz/repository/UseWordRepository.java
- Resolves #
> 기존 Map<>으로 받아 unique하지 않은 리스트를 반환하는 예외가 발생해 List로 받게 변경
- 00
=> fix: enrollUseWords 에러 수정

src/main/java/soongsil/kidbean/server/quiz/repository/UseWordRepository.java
=> refactor: 안쓰는 코드 삭제

src/main/java/soongsil/kidbean/server/global/util/LocalDummyDataInit.java, src/main/java/soongsil/kidbean/server/program/application/ProgramService.java, src/main/java/soongsil/kidbean/server/program/domain/OpenDay.java, src/main/java/soongsil/kidbean/server/program/domain/Program.java, src/main/java/soongsil/kidbean/server/program/dto/request/EnrollProgramRequest.java, src/main/java/soongsil/kidbean/server/program/repository/OpenDayRepository.java, src/main/java/soongsil/kidbean/server/program/repository/init/OpenDayInitializer.java, src/main/java/soongsil/kidbean/server/quiz/application/ImageQuizService.java, src/main/java/soongsil/kidbean/server/quiz/application/WordQuizService.java, src/main/java/soongsil/kidbean/server/quiz/repository/ImageQuizRepository.java, src/main/java/soongsil/kidbean/server/quiz/util/RandNumUtil.java, src/test/java/soongsil/kidbean/server/global/application/config/TestSecurityConfig.java, src/test/java/soongsil/kidbean/server/quiz/application/ImageQuizServiceTest.java, src/test/java/soongsil/kidbean/server/quiz/util/RandNumUtilTest.java, src/test/java/soongsil/kidbean/server/tuning/ImageQuizTuningTest.java, src/test/resources/application.yml
=> refactor: 쿼리 최적화 진행 중

src/main/java/soongsil/kidbean/server/imagequiz/application/ImageQuizService.java, src/main/java/soongsil/kidbean/server/imagequiz/repository/ImageQuizRepository.java, src/main/java/soongsil/kidbean/server/member/domain/Member.java, src/test/java/soongsil/kidbean/server/imagequiz/application/ImageQuizServiceTest.java, src/test/java/soongsil/kidbean/server/tuning/ImageQuizTuningTest.java, src/test/resources/application.yml
> ImageQuiz 조회 성능 최적화
- ImageQuiz 조회 쿼리 최적화 및 index 설정으로 인한 성능 최적화
=> refactor: ImageQuiz 조회 성능 최적화

src/main/java/soongsil/kidbean/server/answerquiz/repository/init/AnswerQuizInitializer.java, src/main/java/soongsil/kidbean/server/auth/application/jwt/JwtTokenProvider.java, src/main/java/soongsil/kidbean/server/imagequiz/application/ImageQuizService.java, src/main/java/soongsil/kidbean/server/imagequiz/domain/ImageQuiz.java, src/main/java/soongsil/kidbean/server/imagequiz/dto/request/ImageQuizUploadRequest.java, src/main/java/soongsil/kidbean/server/imagequiz/repository/ImageQuizRepository.java, src/main/java/soongsil/kidbean/server/imagequiz/repository/init/ImageQuizInitializer.java, src/main/java/soongsil/kidbean/server/member/domain/Member.java, src/main/java/soongsil/kidbean/server/member/repository/MemberRepository.java, src/main/java/soongsil/kidbean/server/member/repository/init/MemberInitializer.java, src/main/java/soongsil/kidbean/server/program/repository/init/ProgramInitializer.java, src/main/java/soongsil/kidbean/server/program/repository/init/StarInitializer.java, src/main/java/soongsil/kidbean/server/quizsolve/repository/init/QuizSolvedInitializer.java, src/main/java/soongsil/kidbean/server/summary/repository/init/ImageScoreInitializer.java, src/main/java/soongsil/kidbean/server/wordquiz/application/WordQuizService.java, src/main/java/soongsil/kidbean/server/wordquiz/domain/WordQuiz.java, src/main/java/soongsil/kidbean/server/wordquiz/dto/response/WordQuizSolveResponse.java, src/main/java/soongsil/kidbean/server/wordquiz/repository/WordQuizRepository.java, src/main/java/soongsil/kidbean/server/wordquiz/repository/init/WordQuizInitializer.java, src/test/java/soongsil/kidbean/server/imagequiz/application/ImageQuizServiceTest.java, src/test/java/soongsil/kidbean/server/wordquiz/application/WordQuizServiceTest.java
> 이미지 퀴즈 조회 성능 최적화
- 이미지 퀴즈 조회 성능 최적화
=> refactor: 이미지 퀴즈 조회 성능 최적화

src/main/java/soongsil/kidbean/server/member/repository/init/MemberInitializer.java
=> fix: 더미 데이터 수정

src/main/java/soongsil/kidbean/server/imagequiz/application/ImageQuizService.java, src/main/java/soongsil/kidbean/server/imagequiz/domain/ImageQuiz.java, src/main/java/soongsil/kidbean/server/imagequiz/dto/request/ImageQuizUploadRequest.java, src/main/java/soongsil/kidbean/server/imagequiz/dto/response/ImageQuizSolveListResponse.java, src/main/java/soongsil/kidbean/server/imagequiz/presentation/ImageQuizController.java, src/main/java/soongsil/kidbean/server/imagequiz/repository/ImageQuizRepository.java, src/main/java/soongsil/kidbean/server/imagequiz/repository/init/ImageQuizInitializer.java, src/main/java/soongsil/kidbean/server/imagequiz/util/ImageQuizCountCache.java, src/test/java/soongsil/kidbean/server/imagequiz/application/ImageQuizServiceTest.java, src/test/java/soongsil/kidbean/server/imagequiz/util/ImageQuizCountCacheTest.java, src/test/java/soongsil/kidbean/server/tuning/ImageQuizTuningTest.java
> ImageQuiz 조회 최적화 완료
- ImageQuiz 조회 최적화 완료
=> [REFACTOR] ImageQuiz 조회 최적화 완료

src/main/java/soongsil/kidbean/server/auth/presentation/filter/JwtFilter.java, src/main/java/soongsil/kidbean/server/auth/util/AuthenticationUtil.java, src/main/java/soongsil/kidbean/server/quizsolve/application/quizscorer/ImageQuizScorer.java, src/main/java/soongsil/kidbean/server/quizsolve/application/quizscorer/WordQuizScorer.java, src/main/java/soongsil/kidbean/server/quizsolve/application/quizsolver/ImageQuizSolver.java, src/main/java/soongsil/kidbean/server/quizsolve/application/quizsolver/WordQuizSolver.java, src/main/java/soongsil/kidbean/server/quizsolve/application/quizsolver/dto/SolvedQuizInfo.java, src/main/java/soongsil/kidbean/server/quizsolve/dto/request/QuizSolvedRequest.java, src/main/java/soongsil/kidbean/server/summary/domain/QuizScore.java, src/test/java/soongsil/kidbean/server/quizsolve/application/QuizSolvedServiceTest.java, src/test/java/soongsil/kidbean/server/quizsolve/application/quizsolver/ImageQuizSolverTest.java, src/test/java/soongsil/kidbean/server/quizsolve/application/quizsolver/WordQuizSolverTest.java, src/test/java/soongsil/kidbean/server/tuning/ImageQuizTuningTest.java, src/test/java/soongsil/kidbean/server/tuning/WordQuizTuningTest.java, src/test/resources/application.yml
> 문제를 중복해서 풀어도 점수 계속 지급
- 문제를 중복해서 풀어도 점수 계속 지급
- 통합 테스트 코드 작성
=> refactor: 문제를 중복해서 풀어도 점수 계속 지급

src/main/java/soongsil/kidbean/server/quizsolve/domain/QuizSolved.java, src/test/java/soongsil/kidbean/server/tuning/ImageQuizConcurrentTest.java, src/test/java/soongsil/kidbean/server/tuning/ImageQuizTuningTest.java, src/test/java/soongsil/kidbean/server/tuning/WordQuizConcurrentTest.java, src/test/resources/application.yml
> ImageQuiz 관련 동시성 테스트 진행
- ImageQuiz 관련 동시성 테스트 진행
=> test: ImageQuiz 관련 동시성 테스트 진행

src/test/java/soongsil/kidbean/server/tuning/ImageQuizConcurrentTest.java, src/test/java/soongsil/kidbean/server/tuning/ImageQuizTuningTest.java, src/test/java/soongsil/kidbean/server/tuning/WordQuizConcurrentTest.java, src/test/resources/application.yml
> 데이터베이스 관련 문제 발생으로 DB 설정 변경
- 데이터베이스 관련 문제 발생으로 DB 설정 변경
=> fix: 데이터베이스 관련 문제 발생으로 DB 설정 변경

src/main/java/soongsil/kidbean/server/quizsolve/application/quizsolver/ImageQuizSolver.java, src/main/java/soongsil/kidbean/server/quizsolve/application/quizsolver/WordQuizSolver.java, src/main/java/soongsil/kidbean/server/summary/domain/QuizScore.java
> QuizScore에 unique 제약 조건 추가
- QuizScore에 unique 제약 조건 추가
=> refactor: QuizScore에 unique 제약 조건 추가

src/test/java/soongsil/kidbean/server/quizsolve/application/quizsolver/ImageQuizSolverTest.java, src/test/java/soongsil/kidbean/server/quizsolve/application/quizsolver/WordQuizSolverTest.java
> Solver 관련 테스트 코드 수정
- Solver 관련 테스트 코드 수정
=> fix: Solver 관련 테스트 코드 수정

src/main/java/soongsil/kidbean/server/auth/application/AuthService.java, src/main/java/soongsil/kidbean/server/imagequiz/application/ImageQuizService.java, src/main/java/soongsil/kidbean/server/imagequiz/application/MemberScoreUpdateStrategy.java, src/main/java/soongsil/kidbean/server/imagequiz/presentation/ImageQuizController.java, src/main/java/soongsil/kidbean/server/member/domain/Member.java, src/main/java/soongsil/kidbean/server/member/repository/MemberRepository.java, src/main/java/soongsil/kidbean/server/quizsolve/application/QuizSolvedService.java, src/main/java/soongsil/kidbean/server/quizsolve/application/quizscorer/ImageQuizScorer.java, src/main/java/soongsil/kidbean/server/quizsolve/application/quizscorer/WordQuizScorer.java, src/main/java/soongsil/kidbean/server/summary/domain/QuizScore.java, src/test/java/soongsil/kidbean/server/tuning/ImageQuizConcurrentTest.java
> 낙관적 락으로 ImageQuiz 문제 풀기 동시성 관리
- 낙관적 락으로 ImageQuiz 문제 풀기 동시성 관리
=> refactor: 낙관적 락으로 ImageQuiz 문제 풀기 동시성 관리

src/test/java/soongsil/kidbean/server/imagequiz/presentation/ImageQuizControllerTest.java, src/test/java/soongsil/kidbean/server/tuning/ImageQuizConcurrentTest.java
> 테스트 코드 관련 수정 사항 반영
- 테스트 코드 관련 수정 사항 반영
=> test: 테스트 코드 관련 수정 사항 반영

.github/workflows/gradle-cicd.yml
> 테스트 BD 설정 github action 파일에 추가
- 테스트 BD 설정 github action 파일에 추가
=> fix: 테스트 BD 설정 github action 파일에 추가

.github/workflows/gradle-cicd.yml, src/test/java/soongsil/kidbean/server/tuning/ImageQuizConcurrentTest.java, src/test/java/soongsil/kidbean/server/tuning/ImageQuizTuningTest.java, src/test/java/soongsil/kidbean/server/tuning/WordQuizConcurrentTest.java
- Resolves #
> 테스트 관련 오류 수정
- 테스트 관련 오류 수정
=> fix: 테스트 관련 오류 수정

src/test/resources/application.yml
- Resolves #
> MySQL8로 Dialect 변경
- MySQL8로 Dialect 변경
=> fix: MySQL8로 Dialect 변경

.github/workflows/gradle-cicd.yml
- Resolves #
> TestDB 설정 CI/CD 파일에 추가
- TestDB 설정 CI/CD 파일에 추가
=> fix: TestDB 설정 CI/CD 파일에 추가

.github/workflows/gradle-cicd.yml, src/test/java/soongsil/kidbean/server/tuning/ImageQuizConcurrentTest.java, src/test/resources/application.yml
- Resolves #
> TestDB H2로 다시 변경 및 native query 사용 테스트 주석 처리
- TestDB H2로 다시 변경 및 native query 사용 테스트 주석 처리
=> fix: TestDB H2로 다시 변경 및 native query 사용 테스트 주석 처리

src/main/java/soongsil/kidbean/server/member/repository/init/MemberInitializer.java
- Resolves #
>  Member 더미 데이터에 QuizCategory 추가
-  Member 더미 데이터에 QuizCategory 추가
=> fix: Member 더미 데이터에 QuizCategory 추가

src/main/java/soongsil/kidbean/server/imagequiz/application/ImageQuizService.java, src/main/java/soongsil/kidbean/server/imagequiz/application/ImageQuizServiceFacade.java, src/main/java/soongsil/kidbean/server/imagequiz/application/MemberScoreUpdateStrategy.java, src/main/java/soongsil/kidbean/server/imagequiz/presentation/ImageQuizController.java, src/main/java/soongsil/kidbean/server/quizsolve/application/QuizSolvedService.java, src/main/java/soongsil/kidbean/server/quizsolve/util/LockUnLockAspect.java, src/test/java/soongsil/kidbean/server/imagequiz/presentation/ImageQuizControllerTest.java, src/test/resources/application.yml
- Resolves #
> Facade 객체로 ImageQuizSolve 진행
- Facade 객체로 ImageQuizSolve 진행
=> refactor: Facade 객체로 ImageQuizSolve 진행

src/main/resources/logback-spring.xml, src/main/resources/logs/common/file-error-appender.xml, src/main/resources/logs/common/file-info-appender.xml, src/main/resources/logs/common/file-warn-appender.xml, src/main/resources/logs/console-appender.xml, src/main/resources/logs/error/file-error-appender.xml, src/main/resources/logs/error/file-info-appender.xml, src/main/resources/logs/error/file-warn-appender.xml
- Resolves #107 
> Logback을 사용해 로그 관리하기
- Logback을 위한 설정 추가 및 관련 파일 추가
=> feat: logback 관련 설정 및 파일 추가

src/main/java/soongsil/kidbean/server/wordquiz/application/WordQuizService.java, src/main/java/soongsil/kidbean/server/wordquiz/repository/WordQuizRepository.java
- Resolves #105 
> WordQuiz N+1 문제 해결
- N+1 문제에 Join fetch 사용
=> refactor: WordQuiz N+1 문제 해결
